//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Lab Metaverse/Controls/SimulatorInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace UnityEngine.InputSystem
{
    public partial class @SimulatorInputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @SimulatorInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""SimulatorInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerGamepad"",
            ""id"": ""df70fa95-8a34-4494-b137-73ab6b9c7d37"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""351f2ccd-1f9f-44bf-9bec-d62ac5c5f408"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""6b444451-8a00-4d00-a97e-f47457f736a8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dpad"",
                    ""type"": ""Value"",
                    ""id"": ""a37a84aa-dbf1-40b9-b789-9f829a05800b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Steer"",
                    ""type"": ""Value"",
                    ""id"": ""fab6fc17-096a-43df-9138-1fdad530e547"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""d6567370-c01d-4721-b0d3-1f67c9d459f7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BrakeReverse"",
                    ""type"": ""Value"",
                    ""id"": ""e59fed34-b820-4ad6-b0dc-022c1f35b256"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HandBrake"",
                    ""type"": ""Button"",
                    ""id"": ""138397f2-45c6-4cf8-8570-4cc0a5649a95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeView"",
                    ""type"": ""Button"",
                    ""id"": ""d4ca48b0-e8f2-41dd-a1d9-a379a37cc2cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextGear"",
                    ""type"": ""Button"",
                    ""id"": ""d3791576-1497-4ca5-828f-3de632f9f620"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevGear"",
                    ""type"": ""Button"",
                    ""id"": ""2b8d4e87-2654-44c3-aaa3-518ffd5720ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLights"",
                    ""type"": ""Button"",
                    ""id"": ""3519e220-ae77-454a-8ee9-2b31ef496d34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLeftTurnLights"",
                    ""type"": ""Button"",
                    ""id"": ""655eecd6-cc28-459e-97a7-f80d48c590cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchRightTurnLights"",
                    ""type"": ""Button"",
                    ""id"": ""fa6d216e-9503-47ba-b328-0d81457595a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetCar"",
                    ""type"": ""Button"",
                    ""id"": ""ea295667-fb5f-4de7-86fa-c621dd534be5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConnectTrailer"",
                    ""type"": ""Button"",
                    ""id"": ""b4af782f-13e6-45b2-9fb5-3b0376e76d42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchAlarm"",
                    ""type"": ""Button"",
                    ""id"": ""ab1da180-ebfd-44e6-803d-7cd8c2ab0a17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""978bfe49-cc26-4a3d-ab7b-7d7a29327403"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1f7a91b-d0fd-4a62-997e-7fb9b69bf235"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93daea04-6b6c-403c-bab8-663f0730d9ae"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""22e5ff94-3e7a-43bc-9ca4-739b52e29204"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d52a28fb-6a15-4625-96e7-088d5d45a897"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""725ac886-05c6-4af5-9835-aba7636e2117"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""945bd24f-1497-4049-b04a-544102df5e74"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f448fb7-dd1e-42b3-af56-e4071d7b3997"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrakeReverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a049c48-3300-4fca-8c2c-d79dcc42a6fb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandBrake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa75bd31-045c-496e-a938-c254ec2a2002"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe902887-509a-4161-a85e-3c67b493964f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2639f33-4c1c-419a-b9bc-428135cbc9c7"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abbed4be-fbb8-44df-aa95-014d3147fac1"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2be2266d-a825-415e-a8b7-cbb3c0ae79a7"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLeftTurnLights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec59c523-84c3-4467-afb2-3e1676eca983"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchRightTurnLights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""056ba78c-59ba-45ca-a2cb-8aa1e3d71578"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9667e8ab-bb05-4a36-a34e-6fd83533c503"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConnectTrailer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a23c665-f8c4-467e-a72a-467176ac673d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAlarm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""50d5c611-19f8-4549-8edd-fbeb337f64ea"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""49c94694-90be-4011-930d-9aa5ebdb2d30"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""13eae6a6-98bc-438d-8dce-af7c625455c3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dpad"",
                    ""type"": ""Value"",
                    ""id"": ""9bea3da7-a8e9-4346-9173-66486e86211f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Steer"",
                    ""type"": ""Value"",
                    ""id"": ""cd3060cb-504c-4e88-a0b5-5bd91e79e70e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""b51f8c35-6634-4779-951d-d1422c522c53"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BrakeReverse"",
                    ""type"": ""Value"",
                    ""id"": ""0902cc17-1636-4fb4-af96-e8ebc12a20b4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HandBrake"",
                    ""type"": ""Button"",
                    ""id"": ""65438fec-d638-40f3-8dd3-7c5f11e2be8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""92b8fd52-bad9-4b62-be8e-897c999f7bb5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeView"",
                    ""type"": ""Button"",
                    ""id"": ""5e0c2d91-82bf-4aee-ad25-69acb4ae964b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextGear"",
                    ""type"": ""Button"",
                    ""id"": ""8f669272-9b1e-4bc2-85f7-6ac49e5ac76f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevGear"",
                    ""type"": ""Button"",
                    ""id"": ""d632b41a-ca7d-4a32-8445-4ccd030323e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLights"",
                    ""type"": ""Button"",
                    ""id"": ""968ed024-8be5-46ce-8f0c-993401d2008a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLeftTurnLights"",
                    ""type"": ""Button"",
                    ""id"": ""dd0cfe58-0180-4733-9c73-a9dcca320810"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchRightTurnLights"",
                    ""type"": ""Button"",
                    ""id"": ""dd61f3b7-f96b-44d8-8c24-56fdbb0d1d82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetCar"",
                    ""type"": ""Button"",
                    ""id"": ""59337102-bf69-471d-8b3e-a4c8f82128e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConnectTrailer"",
                    ""type"": ""Button"",
                    ""id"": ""fc2b8a66-cdab-4775-a544-513af3d36860"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchAlarm"",
                    ""type"": ""Button"",
                    ""id"": ""daccc926-b98f-432b-a697-66c2b4b52bbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear1st"",
                    ""type"": ""Button"",
                    ""id"": ""06fce704-adcd-4f98-ab6d-1484b35ba388"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear2nd"",
                    ""type"": ""Button"",
                    ""id"": ""317bb459-0916-4928-ac35-15ef8fd57a1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear3rd"",
                    ""type"": ""Button"",
                    ""id"": ""74114949-1a60-43e5-b379-9aef816c6f34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear4th"",
                    ""type"": ""Button"",
                    ""id"": ""f4aba16a-dec8-451a-a4e6-1010bc0e5275"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear5th"",
                    ""type"": ""Button"",
                    ""id"": ""6538a2be-64e6-4272-bd18-dfba434ac951"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear6th"",
                    ""type"": ""Button"",
                    ""id"": ""079357ba-9ac5-4339-bd15-61e72d71fc05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearReverse"",
                    ""type"": ""Button"",
                    ""id"": ""0f5f22b6-253a-4b16-9131-61c68bee3283"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""48d7ad8b-e87c-4e4b-b830-b815ca57c97e"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/rz"",
                    ""interactions"": """",
                    ""processors"": ""Invert,Normalize(min=-1,max=1,zero=-1)"",
                    ""groups"": """",
                    ""action"": ""BrakeReverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8020a103-ab4d-4fbb-88ba-399e1936b39f"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandBrake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd64f93d-34d3-4019-9a97-4516b0730de4"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47428f97-c705-41b0-87a5-aafc40c222aa"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4343cba-986d-4d7d-9b07-33d2bf0c8ee6"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0213aa12-e18c-4256-863a-b8938f4eac60"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8449f293-4c71-4ac9-9f57-45dd00dced24"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLeftTurnLights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a96507dd-ac09-448e-8801-975aed0d1bf2"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchRightTurnLights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a9924a4-0e30-4e93-ac38-6d4d18f5073b"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08bef7e3-35ef-41a4-8f0e-2d7bb28c1011"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConnectTrailer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d274ad90-432a-406b-b972-c5535c42d3c9"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAlarm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a901ccab-58be-4696-a3c7-d1ffcf3594ba"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8c0fbc9b-cbf7-4b91-a845-77148178ccb7"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3368a068-fc62-4629-870f-156c961a7b72"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""312f83e8-073f-498c-bdbd-17e8190e0095"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/z"",
                    ""interactions"": """",
                    ""processors"": ""Invert,Normalize(min=-1,max=1,zero=-1)"",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e8454f40-af0b-4ce1-9eaa-744f982a50a2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""acd42e89-3e7c-4507-904f-924d5d5ae843"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""399e16ee-8088-41c6-8afb-e101564ef2c0"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""da03808d-69c6-4413-90d1-ee856a7cdbb2"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button13"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear1st"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8886420-d9ab-4799-b705-7a6963a3bada"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button14"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear2nd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fee452fd-c739-42d4-915c-5b03d2400ffb"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button15"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear3rd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06a3e823-520a-4948-b869-4daf7bb2b413"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button16"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear4th"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3b50fd1-afca-4600-8fb3-0e2959b91c78"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button17"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear5th"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b775ecb-5356-447d-a76b-6cc90bbc27c0"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button18"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear6th"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbf91b62-b643-4936-933f-c85b1378f3c1"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button19"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearReverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""272f6d14-89ba-496f-b7ff-215263d3219f"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c95b2375-e6d9-4b88-9c4c-c5e76515df4b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""7607c7b6-cd76-4816-beef-bd0341cfe950"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""15cef263-9014-4fd5-94d9-4e4a6234a6ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""32b35790-4ed0-4e9a-aa41-69ac6d629449"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3c7022bf-7922-4f7c-a998-c437916075ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0489e84a-4833-4c40-bfae-cea84b696689"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dad70c86-b58c-4b17-88ad-f5e53adf419e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""44b200b1-1557-4083-816c-b22cbdf77ddf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ff527021-f211-4c02-933e-5976594c46ed"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""563fbfdd-0f09-408d-aa75-8642c4f08ef0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb480147-c587-4a33-85ed-eb0ab9942c43"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2bf42165-60bc-42ca-8072-8c13ab40239b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""85d264ad-e0a0-4565-b7ff-1a37edde51ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""74214943-c580-44e4-98eb-ad7eebe17902"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cea9b045-a000-445b-95b8-0c171af70a3b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8607c725-d935-4808-84b1-8354e29bab63"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4cda81dc-9edd-4e03-9d7c-a71a14345d0b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e92bb26-7e3b-4ec4-b06b-3c8f8e498ddc"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82627dcc-3b13-4ba9-841d-e4b746d6553e"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c52c8e0b-8179-41d3-b8a1-d149033bbe86"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4faf7dc9-b979-4210-aa8c-e808e1ef89f5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38c99815-14ea-4617-8627-164d27641299"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24066f69-da47-44f3-a07e-0015fb02eb2e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c191405-5738-4d4b-a523-c6a301dbf754"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // PlayerGamepad
            m_PlayerGamepad = asset.FindActionMap("PlayerGamepad", throwIfNotFound: true);
            m_PlayerGamepad_Move = m_PlayerGamepad.FindAction("Move", throwIfNotFound: true);
            m_PlayerGamepad_Look = m_PlayerGamepad.FindAction("Look", throwIfNotFound: true);
            m_PlayerGamepad_Dpad = m_PlayerGamepad.FindAction("Dpad", throwIfNotFound: true);
            m_PlayerGamepad_Steer = m_PlayerGamepad.FindAction("Steer", throwIfNotFound: true);
            m_PlayerGamepad_Acceleration = m_PlayerGamepad.FindAction("Acceleration", throwIfNotFound: true);
            m_PlayerGamepad_BrakeReverse = m_PlayerGamepad.FindAction("BrakeReverse", throwIfNotFound: true);
            m_PlayerGamepad_HandBrake = m_PlayerGamepad.FindAction("HandBrake", throwIfNotFound: true);
            m_PlayerGamepad_ChangeView = m_PlayerGamepad.FindAction("ChangeView", throwIfNotFound: true);
            m_PlayerGamepad_NextGear = m_PlayerGamepad.FindAction("NextGear", throwIfNotFound: true);
            m_PlayerGamepad_PrevGear = m_PlayerGamepad.FindAction("PrevGear", throwIfNotFound: true);
            m_PlayerGamepad_SwitchLights = m_PlayerGamepad.FindAction("SwitchLights", throwIfNotFound: true);
            m_PlayerGamepad_SwitchLeftTurnLights = m_PlayerGamepad.FindAction("SwitchLeftTurnLights", throwIfNotFound: true);
            m_PlayerGamepad_SwitchRightTurnLights = m_PlayerGamepad.FindAction("SwitchRightTurnLights", throwIfNotFound: true);
            m_PlayerGamepad_ResetCar = m_PlayerGamepad.FindAction("ResetCar", throwIfNotFound: true);
            m_PlayerGamepad_ConnectTrailer = m_PlayerGamepad.FindAction("ConnectTrailer", throwIfNotFound: true);
            m_PlayerGamepad_SwitchAlarm = m_PlayerGamepad.FindAction("SwitchAlarm", throwIfNotFound: true);
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
            m_Player_Dpad = m_Player.FindAction("Dpad", throwIfNotFound: true);
            m_Player_Steer = m_Player.FindAction("Steer", throwIfNotFound: true);
            m_Player_Acceleration = m_Player.FindAction("Acceleration", throwIfNotFound: true);
            m_Player_BrakeReverse = m_Player.FindAction("BrakeReverse", throwIfNotFound: true);
            m_Player_HandBrake = m_Player.FindAction("HandBrake", throwIfNotFound: true);
            m_Player_Clutch = m_Player.FindAction("Clutch", throwIfNotFound: true);
            m_Player_ChangeView = m_Player.FindAction("ChangeView", throwIfNotFound: true);
            m_Player_NextGear = m_Player.FindAction("NextGear", throwIfNotFound: true);
            m_Player_PrevGear = m_Player.FindAction("PrevGear", throwIfNotFound: true);
            m_Player_SwitchLights = m_Player.FindAction("SwitchLights", throwIfNotFound: true);
            m_Player_SwitchLeftTurnLights = m_Player.FindAction("SwitchLeftTurnLights", throwIfNotFound: true);
            m_Player_SwitchRightTurnLights = m_Player.FindAction("SwitchRightTurnLights", throwIfNotFound: true);
            m_Player_ResetCar = m_Player.FindAction("ResetCar", throwIfNotFound: true);
            m_Player_ConnectTrailer = m_Player.FindAction("ConnectTrailer", throwIfNotFound: true);
            m_Player_SwitchAlarm = m_Player.FindAction("SwitchAlarm", throwIfNotFound: true);
            m_Player_Gear1st = m_Player.FindAction("Gear1st", throwIfNotFound: true);
            m_Player_Gear2nd = m_Player.FindAction("Gear2nd", throwIfNotFound: true);
            m_Player_Gear3rd = m_Player.FindAction("Gear3rd", throwIfNotFound: true);
            m_Player_Gear4th = m_Player.FindAction("Gear4th", throwIfNotFound: true);
            m_Player_Gear5th = m_Player.FindAction("Gear5th", throwIfNotFound: true);
            m_Player_Gear6th = m_Player.FindAction("Gear6th", throwIfNotFound: true);
            m_Player_GearReverse = m_Player.FindAction("GearReverse", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
            m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
            m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
            m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
            m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
            m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
            m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
            m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PlayerGamepad
        private readonly InputActionMap m_PlayerGamepad;
        private List<IPlayerGamepadActions> m_PlayerGamepadActionsCallbackInterfaces = new List<IPlayerGamepadActions>();
        private readonly InputAction m_PlayerGamepad_Move;
        private readonly InputAction m_PlayerGamepad_Look;
        private readonly InputAction m_PlayerGamepad_Dpad;
        private readonly InputAction m_PlayerGamepad_Steer;
        private readonly InputAction m_PlayerGamepad_Acceleration;
        private readonly InputAction m_PlayerGamepad_BrakeReverse;
        private readonly InputAction m_PlayerGamepad_HandBrake;
        private readonly InputAction m_PlayerGamepad_ChangeView;
        private readonly InputAction m_PlayerGamepad_NextGear;
        private readonly InputAction m_PlayerGamepad_PrevGear;
        private readonly InputAction m_PlayerGamepad_SwitchLights;
        private readonly InputAction m_PlayerGamepad_SwitchLeftTurnLights;
        private readonly InputAction m_PlayerGamepad_SwitchRightTurnLights;
        private readonly InputAction m_PlayerGamepad_ResetCar;
        private readonly InputAction m_PlayerGamepad_ConnectTrailer;
        private readonly InputAction m_PlayerGamepad_SwitchAlarm;
        public struct PlayerGamepadActions
        {
            private @SimulatorInputActions m_Wrapper;
            public PlayerGamepadActions(@SimulatorInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_PlayerGamepad_Move;
            public InputAction @Look => m_Wrapper.m_PlayerGamepad_Look;
            public InputAction @Dpad => m_Wrapper.m_PlayerGamepad_Dpad;
            public InputAction @Steer => m_Wrapper.m_PlayerGamepad_Steer;
            public InputAction @Acceleration => m_Wrapper.m_PlayerGamepad_Acceleration;
            public InputAction @BrakeReverse => m_Wrapper.m_PlayerGamepad_BrakeReverse;
            public InputAction @HandBrake => m_Wrapper.m_PlayerGamepad_HandBrake;
            public InputAction @ChangeView => m_Wrapper.m_PlayerGamepad_ChangeView;
            public InputAction @NextGear => m_Wrapper.m_PlayerGamepad_NextGear;
            public InputAction @PrevGear => m_Wrapper.m_PlayerGamepad_PrevGear;
            public InputAction @SwitchLights => m_Wrapper.m_PlayerGamepad_SwitchLights;
            public InputAction @SwitchLeftTurnLights => m_Wrapper.m_PlayerGamepad_SwitchLeftTurnLights;
            public InputAction @SwitchRightTurnLights => m_Wrapper.m_PlayerGamepad_SwitchRightTurnLights;
            public InputAction @ResetCar => m_Wrapper.m_PlayerGamepad_ResetCar;
            public InputAction @ConnectTrailer => m_Wrapper.m_PlayerGamepad_ConnectTrailer;
            public InputAction @SwitchAlarm => m_Wrapper.m_PlayerGamepad_SwitchAlarm;
            public InputActionMap Get() { return m_Wrapper.m_PlayerGamepad; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerGamepadActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerGamepadActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerGamepadActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerGamepadActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Dpad.started += instance.OnDpad;
                @Dpad.performed += instance.OnDpad;
                @Dpad.canceled += instance.OnDpad;
                @Steer.started += instance.OnSteer;
                @Steer.performed += instance.OnSteer;
                @Steer.canceled += instance.OnSteer;
                @Acceleration.started += instance.OnAcceleration;
                @Acceleration.performed += instance.OnAcceleration;
                @Acceleration.canceled += instance.OnAcceleration;
                @BrakeReverse.started += instance.OnBrakeReverse;
                @BrakeReverse.performed += instance.OnBrakeReverse;
                @BrakeReverse.canceled += instance.OnBrakeReverse;
                @HandBrake.started += instance.OnHandBrake;
                @HandBrake.performed += instance.OnHandBrake;
                @HandBrake.canceled += instance.OnHandBrake;
                @ChangeView.started += instance.OnChangeView;
                @ChangeView.performed += instance.OnChangeView;
                @ChangeView.canceled += instance.OnChangeView;
                @NextGear.started += instance.OnNextGear;
                @NextGear.performed += instance.OnNextGear;
                @NextGear.canceled += instance.OnNextGear;
                @PrevGear.started += instance.OnPrevGear;
                @PrevGear.performed += instance.OnPrevGear;
                @PrevGear.canceled += instance.OnPrevGear;
                @SwitchLights.started += instance.OnSwitchLights;
                @SwitchLights.performed += instance.OnSwitchLights;
                @SwitchLights.canceled += instance.OnSwitchLights;
                @SwitchLeftTurnLights.started += instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.performed += instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.canceled += instance.OnSwitchLeftTurnLights;
                @SwitchRightTurnLights.started += instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.performed += instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.canceled += instance.OnSwitchRightTurnLights;
                @ResetCar.started += instance.OnResetCar;
                @ResetCar.performed += instance.OnResetCar;
                @ResetCar.canceled += instance.OnResetCar;
                @ConnectTrailer.started += instance.OnConnectTrailer;
                @ConnectTrailer.performed += instance.OnConnectTrailer;
                @ConnectTrailer.canceled += instance.OnConnectTrailer;
                @SwitchAlarm.started += instance.OnSwitchAlarm;
                @SwitchAlarm.performed += instance.OnSwitchAlarm;
                @SwitchAlarm.canceled += instance.OnSwitchAlarm;
            }

            private void UnregisterCallbacks(IPlayerGamepadActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Look.started -= instance.OnLook;
                @Look.performed -= instance.OnLook;
                @Look.canceled -= instance.OnLook;
                @Dpad.started -= instance.OnDpad;
                @Dpad.performed -= instance.OnDpad;
                @Dpad.canceled -= instance.OnDpad;
                @Steer.started -= instance.OnSteer;
                @Steer.performed -= instance.OnSteer;
                @Steer.canceled -= instance.OnSteer;
                @Acceleration.started -= instance.OnAcceleration;
                @Acceleration.performed -= instance.OnAcceleration;
                @Acceleration.canceled -= instance.OnAcceleration;
                @BrakeReverse.started -= instance.OnBrakeReverse;
                @BrakeReverse.performed -= instance.OnBrakeReverse;
                @BrakeReverse.canceled -= instance.OnBrakeReverse;
                @HandBrake.started -= instance.OnHandBrake;
                @HandBrake.performed -= instance.OnHandBrake;
                @HandBrake.canceled -= instance.OnHandBrake;
                @ChangeView.started -= instance.OnChangeView;
                @ChangeView.performed -= instance.OnChangeView;
                @ChangeView.canceled -= instance.OnChangeView;
                @NextGear.started -= instance.OnNextGear;
                @NextGear.performed -= instance.OnNextGear;
                @NextGear.canceled -= instance.OnNextGear;
                @PrevGear.started -= instance.OnPrevGear;
                @PrevGear.performed -= instance.OnPrevGear;
                @PrevGear.canceled -= instance.OnPrevGear;
                @SwitchLights.started -= instance.OnSwitchLights;
                @SwitchLights.performed -= instance.OnSwitchLights;
                @SwitchLights.canceled -= instance.OnSwitchLights;
                @SwitchLeftTurnLights.started -= instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.performed -= instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.canceled -= instance.OnSwitchLeftTurnLights;
                @SwitchRightTurnLights.started -= instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.performed -= instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.canceled -= instance.OnSwitchRightTurnLights;
                @ResetCar.started -= instance.OnResetCar;
                @ResetCar.performed -= instance.OnResetCar;
                @ResetCar.canceled -= instance.OnResetCar;
                @ConnectTrailer.started -= instance.OnConnectTrailer;
                @ConnectTrailer.performed -= instance.OnConnectTrailer;
                @ConnectTrailer.canceled -= instance.OnConnectTrailer;
                @SwitchAlarm.started -= instance.OnSwitchAlarm;
                @SwitchAlarm.performed -= instance.OnSwitchAlarm;
                @SwitchAlarm.canceled -= instance.OnSwitchAlarm;
            }

            public void RemoveCallbacks(IPlayerGamepadActions instance)
            {
                if (m_Wrapper.m_PlayerGamepadActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayerGamepadActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerGamepadActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerGamepadActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerGamepadActions @PlayerGamepad => new PlayerGamepadActions(this);

        // Player
        private readonly InputActionMap m_Player;
        private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_Look;
        private readonly InputAction m_Player_Dpad;
        private readonly InputAction m_Player_Steer;
        private readonly InputAction m_Player_Acceleration;
        private readonly InputAction m_Player_BrakeReverse;
        private readonly InputAction m_Player_HandBrake;
        private readonly InputAction m_Player_Clutch;
        private readonly InputAction m_Player_ChangeView;
        private readonly InputAction m_Player_NextGear;
        private readonly InputAction m_Player_PrevGear;
        private readonly InputAction m_Player_SwitchLights;
        private readonly InputAction m_Player_SwitchLeftTurnLights;
        private readonly InputAction m_Player_SwitchRightTurnLights;
        private readonly InputAction m_Player_ResetCar;
        private readonly InputAction m_Player_ConnectTrailer;
        private readonly InputAction m_Player_SwitchAlarm;
        private readonly InputAction m_Player_Gear1st;
        private readonly InputAction m_Player_Gear2nd;
        private readonly InputAction m_Player_Gear3rd;
        private readonly InputAction m_Player_Gear4th;
        private readonly InputAction m_Player_Gear5th;
        private readonly InputAction m_Player_Gear6th;
        private readonly InputAction m_Player_GearReverse;
        public struct PlayerActions
        {
            private @SimulatorInputActions m_Wrapper;
            public PlayerActions(@SimulatorInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @Look => m_Wrapper.m_Player_Look;
            public InputAction @Dpad => m_Wrapper.m_Player_Dpad;
            public InputAction @Steer => m_Wrapper.m_Player_Steer;
            public InputAction @Acceleration => m_Wrapper.m_Player_Acceleration;
            public InputAction @BrakeReverse => m_Wrapper.m_Player_BrakeReverse;
            public InputAction @HandBrake => m_Wrapper.m_Player_HandBrake;
            public InputAction @Clutch => m_Wrapper.m_Player_Clutch;
            public InputAction @ChangeView => m_Wrapper.m_Player_ChangeView;
            public InputAction @NextGear => m_Wrapper.m_Player_NextGear;
            public InputAction @PrevGear => m_Wrapper.m_Player_PrevGear;
            public InputAction @SwitchLights => m_Wrapper.m_Player_SwitchLights;
            public InputAction @SwitchLeftTurnLights => m_Wrapper.m_Player_SwitchLeftTurnLights;
            public InputAction @SwitchRightTurnLights => m_Wrapper.m_Player_SwitchRightTurnLights;
            public InputAction @ResetCar => m_Wrapper.m_Player_ResetCar;
            public InputAction @ConnectTrailer => m_Wrapper.m_Player_ConnectTrailer;
            public InputAction @SwitchAlarm => m_Wrapper.m_Player_SwitchAlarm;
            public InputAction @Gear1st => m_Wrapper.m_Player_Gear1st;
            public InputAction @Gear2nd => m_Wrapper.m_Player_Gear2nd;
            public InputAction @Gear3rd => m_Wrapper.m_Player_Gear3rd;
            public InputAction @Gear4th => m_Wrapper.m_Player_Gear4th;
            public InputAction @Gear5th => m_Wrapper.m_Player_Gear5th;
            public InputAction @Gear6th => m_Wrapper.m_Player_Gear6th;
            public InputAction @GearReverse => m_Wrapper.m_Player_GearReverse;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Dpad.started += instance.OnDpad;
                @Dpad.performed += instance.OnDpad;
                @Dpad.canceled += instance.OnDpad;
                @Steer.started += instance.OnSteer;
                @Steer.performed += instance.OnSteer;
                @Steer.canceled += instance.OnSteer;
                @Acceleration.started += instance.OnAcceleration;
                @Acceleration.performed += instance.OnAcceleration;
                @Acceleration.canceled += instance.OnAcceleration;
                @BrakeReverse.started += instance.OnBrakeReverse;
                @BrakeReverse.performed += instance.OnBrakeReverse;
                @BrakeReverse.canceled += instance.OnBrakeReverse;
                @HandBrake.started += instance.OnHandBrake;
                @HandBrake.performed += instance.OnHandBrake;
                @HandBrake.canceled += instance.OnHandBrake;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @ChangeView.started += instance.OnChangeView;
                @ChangeView.performed += instance.OnChangeView;
                @ChangeView.canceled += instance.OnChangeView;
                @NextGear.started += instance.OnNextGear;
                @NextGear.performed += instance.OnNextGear;
                @NextGear.canceled += instance.OnNextGear;
                @PrevGear.started += instance.OnPrevGear;
                @PrevGear.performed += instance.OnPrevGear;
                @PrevGear.canceled += instance.OnPrevGear;
                @SwitchLights.started += instance.OnSwitchLights;
                @SwitchLights.performed += instance.OnSwitchLights;
                @SwitchLights.canceled += instance.OnSwitchLights;
                @SwitchLeftTurnLights.started += instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.performed += instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.canceled += instance.OnSwitchLeftTurnLights;
                @SwitchRightTurnLights.started += instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.performed += instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.canceled += instance.OnSwitchRightTurnLights;
                @ResetCar.started += instance.OnResetCar;
                @ResetCar.performed += instance.OnResetCar;
                @ResetCar.canceled += instance.OnResetCar;
                @ConnectTrailer.started += instance.OnConnectTrailer;
                @ConnectTrailer.performed += instance.OnConnectTrailer;
                @ConnectTrailer.canceled += instance.OnConnectTrailer;
                @SwitchAlarm.started += instance.OnSwitchAlarm;
                @SwitchAlarm.performed += instance.OnSwitchAlarm;
                @SwitchAlarm.canceled += instance.OnSwitchAlarm;
                @Gear1st.started += instance.OnGear1st;
                @Gear1st.performed += instance.OnGear1st;
                @Gear1st.canceled += instance.OnGear1st;
                @Gear2nd.started += instance.OnGear2nd;
                @Gear2nd.performed += instance.OnGear2nd;
                @Gear2nd.canceled += instance.OnGear2nd;
                @Gear3rd.started += instance.OnGear3rd;
                @Gear3rd.performed += instance.OnGear3rd;
                @Gear3rd.canceled += instance.OnGear3rd;
                @Gear4th.started += instance.OnGear4th;
                @Gear4th.performed += instance.OnGear4th;
                @Gear4th.canceled += instance.OnGear4th;
                @Gear5th.started += instance.OnGear5th;
                @Gear5th.performed += instance.OnGear5th;
                @Gear5th.canceled += instance.OnGear5th;
                @Gear6th.started += instance.OnGear6th;
                @Gear6th.performed += instance.OnGear6th;
                @Gear6th.canceled += instance.OnGear6th;
                @GearReverse.started += instance.OnGearReverse;
                @GearReverse.performed += instance.OnGearReverse;
                @GearReverse.canceled += instance.OnGearReverse;
            }

            private void UnregisterCallbacks(IPlayerActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Look.started -= instance.OnLook;
                @Look.performed -= instance.OnLook;
                @Look.canceled -= instance.OnLook;
                @Dpad.started -= instance.OnDpad;
                @Dpad.performed -= instance.OnDpad;
                @Dpad.canceled -= instance.OnDpad;
                @Steer.started -= instance.OnSteer;
                @Steer.performed -= instance.OnSteer;
                @Steer.canceled -= instance.OnSteer;
                @Acceleration.started -= instance.OnAcceleration;
                @Acceleration.performed -= instance.OnAcceleration;
                @Acceleration.canceled -= instance.OnAcceleration;
                @BrakeReverse.started -= instance.OnBrakeReverse;
                @BrakeReverse.performed -= instance.OnBrakeReverse;
                @BrakeReverse.canceled -= instance.OnBrakeReverse;
                @HandBrake.started -= instance.OnHandBrake;
                @HandBrake.performed -= instance.OnHandBrake;
                @HandBrake.canceled -= instance.OnHandBrake;
                @Clutch.started -= instance.OnClutch;
                @Clutch.performed -= instance.OnClutch;
                @Clutch.canceled -= instance.OnClutch;
                @ChangeView.started -= instance.OnChangeView;
                @ChangeView.performed -= instance.OnChangeView;
                @ChangeView.canceled -= instance.OnChangeView;
                @NextGear.started -= instance.OnNextGear;
                @NextGear.performed -= instance.OnNextGear;
                @NextGear.canceled -= instance.OnNextGear;
                @PrevGear.started -= instance.OnPrevGear;
                @PrevGear.performed -= instance.OnPrevGear;
                @PrevGear.canceled -= instance.OnPrevGear;
                @SwitchLights.started -= instance.OnSwitchLights;
                @SwitchLights.performed -= instance.OnSwitchLights;
                @SwitchLights.canceled -= instance.OnSwitchLights;
                @SwitchLeftTurnLights.started -= instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.performed -= instance.OnSwitchLeftTurnLights;
                @SwitchLeftTurnLights.canceled -= instance.OnSwitchLeftTurnLights;
                @SwitchRightTurnLights.started -= instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.performed -= instance.OnSwitchRightTurnLights;
                @SwitchRightTurnLights.canceled -= instance.OnSwitchRightTurnLights;
                @ResetCar.started -= instance.OnResetCar;
                @ResetCar.performed -= instance.OnResetCar;
                @ResetCar.canceled -= instance.OnResetCar;
                @ConnectTrailer.started -= instance.OnConnectTrailer;
                @ConnectTrailer.performed -= instance.OnConnectTrailer;
                @ConnectTrailer.canceled -= instance.OnConnectTrailer;
                @SwitchAlarm.started -= instance.OnSwitchAlarm;
                @SwitchAlarm.performed -= instance.OnSwitchAlarm;
                @SwitchAlarm.canceled -= instance.OnSwitchAlarm;
                @Gear1st.started -= instance.OnGear1st;
                @Gear1st.performed -= instance.OnGear1st;
                @Gear1st.canceled -= instance.OnGear1st;
                @Gear2nd.started -= instance.OnGear2nd;
                @Gear2nd.performed -= instance.OnGear2nd;
                @Gear2nd.canceled -= instance.OnGear2nd;
                @Gear3rd.started -= instance.OnGear3rd;
                @Gear3rd.performed -= instance.OnGear3rd;
                @Gear3rd.canceled -= instance.OnGear3rd;
                @Gear4th.started -= instance.OnGear4th;
                @Gear4th.performed -= instance.OnGear4th;
                @Gear4th.canceled -= instance.OnGear4th;
                @Gear5th.started -= instance.OnGear5th;
                @Gear5th.performed -= instance.OnGear5th;
                @Gear5th.canceled -= instance.OnGear5th;
                @Gear6th.started -= instance.OnGear6th;
                @Gear6th.performed -= instance.OnGear6th;
                @Gear6th.canceled -= instance.OnGear6th;
                @GearReverse.started -= instance.OnGearReverse;
                @GearReverse.performed -= instance.OnGearReverse;
                @GearReverse.canceled -= instance.OnGearReverse;
            }

            public void RemoveCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerActions @Player => new PlayerActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
        private readonly InputAction m_UI_Navigate;
        private readonly InputAction m_UI_Submit;
        private readonly InputAction m_UI_Cancel;
        private readonly InputAction m_UI_Point;
        private readonly InputAction m_UI_Click;
        private readonly InputAction m_UI_ScrollWheel;
        private readonly InputAction m_UI_MiddleClick;
        private readonly InputAction m_UI_RightClick;
        public struct UIActions
        {
            private @SimulatorInputActions m_Wrapper;
            public UIActions(@SimulatorInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
            public InputAction @Submit => m_Wrapper.m_UI_Submit;
            public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
            public InputAction @Point => m_Wrapper.m_UI_Point;
            public InputAction @Click => m_Wrapper.m_UI_Click;
            public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
            public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
            public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void AddCallbacks(IUIActions instance)
            {
                if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
            }

            private void UnregisterCallbacks(IUIActions instance)
            {
                @Navigate.started -= instance.OnNavigate;
                @Navigate.performed -= instance.OnNavigate;
                @Navigate.canceled -= instance.OnNavigate;
                @Submit.started -= instance.OnSubmit;
                @Submit.performed -= instance.OnSubmit;
                @Submit.canceled -= instance.OnSubmit;
                @Cancel.started -= instance.OnCancel;
                @Cancel.performed -= instance.OnCancel;
                @Cancel.canceled -= instance.OnCancel;
                @Point.started -= instance.OnPoint;
                @Point.performed -= instance.OnPoint;
                @Point.canceled -= instance.OnPoint;
                @Click.started -= instance.OnClick;
                @Click.performed -= instance.OnClick;
                @Click.canceled -= instance.OnClick;
                @ScrollWheel.started -= instance.OnScrollWheel;
                @ScrollWheel.performed -= instance.OnScrollWheel;
                @ScrollWheel.canceled -= instance.OnScrollWheel;
                @MiddleClick.started -= instance.OnMiddleClick;
                @MiddleClick.performed -= instance.OnMiddleClick;
                @MiddleClick.canceled -= instance.OnMiddleClick;
                @RightClick.started -= instance.OnRightClick;
                @RightClick.performed -= instance.OnRightClick;
                @RightClick.canceled -= instance.OnRightClick;
            }

            public void RemoveCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIActions instance)
            {
                foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIActions @UI => new UIActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        private int m_TouchSchemeIndex = -1;
        public InputControlScheme TouchScheme
        {
            get
            {
                if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
                return asset.controlSchemes[m_TouchSchemeIndex];
            }
        }
        private int m_JoystickSchemeIndex = -1;
        public InputControlScheme JoystickScheme
        {
            get
            {
                if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
                return asset.controlSchemes[m_JoystickSchemeIndex];
            }
        }
        private int m_XRSchemeIndex = -1;
        public InputControlScheme XRScheme
        {
            get
            {
                if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
                return asset.controlSchemes[m_XRSchemeIndex];
            }
        }
        public interface IPlayerGamepadActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnDpad(InputAction.CallbackContext context);
            void OnSteer(InputAction.CallbackContext context);
            void OnAcceleration(InputAction.CallbackContext context);
            void OnBrakeReverse(InputAction.CallbackContext context);
            void OnHandBrake(InputAction.CallbackContext context);
            void OnChangeView(InputAction.CallbackContext context);
            void OnNextGear(InputAction.CallbackContext context);
            void OnPrevGear(InputAction.CallbackContext context);
            void OnSwitchLights(InputAction.CallbackContext context);
            void OnSwitchLeftTurnLights(InputAction.CallbackContext context);
            void OnSwitchRightTurnLights(InputAction.CallbackContext context);
            void OnResetCar(InputAction.CallbackContext context);
            void OnConnectTrailer(InputAction.CallbackContext context);
            void OnSwitchAlarm(InputAction.CallbackContext context);
        }
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnDpad(InputAction.CallbackContext context);
            void OnSteer(InputAction.CallbackContext context);
            void OnAcceleration(InputAction.CallbackContext context);
            void OnBrakeReverse(InputAction.CallbackContext context);
            void OnHandBrake(InputAction.CallbackContext context);
            void OnClutch(InputAction.CallbackContext context);
            void OnChangeView(InputAction.CallbackContext context);
            void OnNextGear(InputAction.CallbackContext context);
            void OnPrevGear(InputAction.CallbackContext context);
            void OnSwitchLights(InputAction.CallbackContext context);
            void OnSwitchLeftTurnLights(InputAction.CallbackContext context);
            void OnSwitchRightTurnLights(InputAction.CallbackContext context);
            void OnResetCar(InputAction.CallbackContext context);
            void OnConnectTrailer(InputAction.CallbackContext context);
            void OnSwitchAlarm(InputAction.CallbackContext context);
            void OnGear1st(InputAction.CallbackContext context);
            void OnGear2nd(InputAction.CallbackContext context);
            void OnGear3rd(InputAction.CallbackContext context);
            void OnGear4th(InputAction.CallbackContext context);
            void OnGear5th(InputAction.CallbackContext context);
            void OnGear6th(InputAction.CallbackContext context);
            void OnGearReverse(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnScrollWheel(InputAction.CallbackContext context);
            void OnMiddleClick(InputAction.CallbackContext context);
            void OnRightClick(InputAction.CallbackContext context);
        }
    }
}
